---
keepalived_vip_address: '{{ network | ipv4(keepalived_vip_fourth_byte) | ipv4("address") }}'
keepalived_vip_prefix: '{{ network | ipv4(keepalived_vip_fourth_byte) | ipv4("prefix") }}'
keepalived_notify_to: 'admin@{{ domain }}'
keepalived_notify_from: '{{ inventory_hostname }}@{{ domain }}'

primary_group: '{{ groups["k3s_primary_masters"] | list }}'
is_primary: '{{ (inventory_hostname in primary_group) | bool }}'

manifests_path_prefix: '/home/ansible/manifests'

calico_network: '192.168.0.0/16'
...
# vim: set filetype=yaml
