---
- name: 'Create directories'
  loop: '{{ helm_configs }}'
  file:
    path: '{{ item | dirname }}'
    state: 'directory'

- name: 'Configure helm'
  loop: '{{ helm_configs }}'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'

- name: 'Install Helm on RHEL'
  when: 'distro == "rhel"'
  import_tasks: 'rhel_install.yml'
...
# vim: set filetype=yaml
