---
- name: 'Install nodes'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tasks:
    - name: 'Create local repo mountpoint'
      register: 'reg_mkdir'
      vars:
        e_readonly: 'Read-only file system'
      failed_when:
        - 'reg_mkdir.rc != 0'
        - 'e_readonly not in reg_mkdir.module_stdout'
      file:
        path: '/mnt/disc'
        state: 'directory'
        mode: '0000'

    - name: 'Add local repo mount to fstab'
      lineinfile:
        path: '/etc/fstab'
        line: '/dev/sr0  /mnt/disc  iso9660  ro  0  0'

    - name: 'Mount local repo image'
      register: 'reg_mount'
      vars:
        e_notfound: "can't find in /etc/fstab."
        e_already: 'already mounted'
      changed_when:
        - 'reg_mount.rc != 0'
        - 'e_already not in reg_mount.stderr'
      failed_when:
        - 'reg_mount.rc != 0'
        - 'e_notfound in reg_mount.stderr'

      command:
        argv:
          - '/bin/mount'
          - '/mnt/disc'

    - name: 'Install keepalived'
      package:
        name: 'keepalived'
...
