---
- name: 'Prepare all hosts generically'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'system_configure'
    # - 'iptables_legacy_install'
    - { name: 'yum_prepare', when: 'distro == "rhel"' }
    - { name: 'xbps_prepare', when: 'distro == "void"' }

- name: 'Prepare node hosts for k3s'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_prepare'

- name: 'Bootstrap k3s master nodes'
  hosts: 'k3s_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'keepalived_install'
    - 'k3s_master_bootstrap'

- name: 'Bootstrap agents'
  hosts: 'k3s_agents'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_agents'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_agent_bootstrap'

- name: 'Install Rancher Admin'
  hosts: 'rancher'
  gather_facts: no
  become: yes
  tags:
    - 'rancher'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rancher_install'

- name: 'Rolling restart cluster'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'rolling_restart'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rolling_restart'
...
# vim: set filetype=yaml
