---
- name: 'Prepare all hosts generically'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - { name: 'rhel_prepare', when: 'distro == "rhel"' }
    - { name: 'void_prepare', when: 'distro == "void"' }
    - 'system_configure'

- name: 'Check local project resources'
  hosts: 'k3s_primary_masters'
  connection: 'local'
  run_once: yes
  become: no
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'project_prepare'

- name: 'Prepare node hosts for k3s'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_prepare'
    - 'k3s_fetch'         # depends on system_configure
    - 'calico_fetch'
    - 'longhorn_fetch'
    - 'metallb_fetch'
    - 'nginx_fetch'
    - 'certmgr_fetch'

- name: 'Generate random server token for cluster'
  hosts: 'k3s_primary_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_master_generate'

- name: 'Bootstrap k3s master nodes'
  hosts: 'k3s_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'helm_install'
    - 'keepalived_install'
    - 'k3s_master_bootstrap'

- name: 'Install manifests'
  hosts: 'k3s_primary_masters'  # should be only one
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'calico_install'
    - 'longhorn_install'
    # add registry later, keep simple for now
    - 'metallb_install'
    - 'nginx_ingress_install'
    - 'cert_manager_install'

- name: 'Bootstrap k3s agents nodes'
  hosts: 'k3s_agents'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_agents'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_agent_bootstrap'
    - 'k3s_agent_post'

- name: 'Install user interface'
  hosts: 'interface'
  gather_facts: no
  become: yes
  tags:
    - 'interface'
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'interface_install'

- name: 'Rolling restart cluster'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'rolling_restart'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rolling_restart'

- name: 'Purge k3s cluster'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'delete_cluster'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'cluster_delete'
...
# vim: set filetype=yaml
