---
- name: 'Check local project resources'
  hosts: 'k3s_primary_masters'
  connection: 'local'
  run_once: yes
  become: no
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'project_prepare'

- name: 'Prepare RHEL hosts generically'
  hosts: 'rhel'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rhel_prepare'
    - 'system_configure'

- name: 'Prepare Void hosts generically'
  hosts: 'void'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'void_prepare'
    - 'system_configure'

- name: 'Prepare node hosts for k3s'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_fetch'         # requires fact set by system_configure
    - 'k3s_prepare'       # will fail if project_prepare didn't complete once
    - 'calico_fetch'
    - 'longhorn_fetch'
    - 'metallb_fetch'
    - 'emissary_fetch'
    - 'certmgr_fetch'
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Generate random server token for cluster'
  hosts: 'k3s_primary_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_master_generate'

- name: 'Bootstrap k3s master nodes'
  hosts: 'k3s_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    # - 'helm_install'      # not using Helm currently
    - 'k3s_master_bootstrap'

- name: 'Deploy software manifests'
  hosts: 'k3s_primary_masters'  # should be only one
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'calico_install'
    - 'longhorn_install'
    - 'metallb_install'
    - 'cert_manager_install'
    - 'emissary_install'
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Apply patch manifests'  # aka modify default settings
  hosts: 'k3s_primary_masters'  # should be only one
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'longhorn_patch'
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Install config manifests'
  hosts: 'k3s_primary_masters'  # should be only one
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_masters'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'metallb_config'
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Bootstrap k3s agents nodes'
  hosts: 'k3s_agents'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'bootstrap_agents'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_agent_bootstrap'
    - 'k3s_agent_post'

- name: 'Install user interface'
  hosts: 'interface'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap_interface'
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'interface_install'

- name: 'Alert all consoles in the cluster'
  hosts: 'all'
  gather_facts: no
  become: no
  tags:
    - 'allwall'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'all_wall'

- name: 'Rolling restart cluster'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'rolling_restart'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rolling_restart'

- name: 'Purge k3s cluster'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'delete_cluster'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'cluster_delete'
...
# vim: set filetype=yaml
