---
- name: 'Ready local project resources'
  hosts: 'all'
  connection: 'local'  # /!\
  run_once: yes
  become: no
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_ready'

- name: 'Ready all targets'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'guest_ready'

- name: 'Ready RHEL targets'
  hosts: 'rhel'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rhel_ready'

- name: 'Ready Void targets'
  hosts: 'void'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'void_ready'

- name: 'Base install'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'nodes_ready'
    - 'images_ready'
    - 'k3s_base_install' # will fail if k3s_ready didn't complete once
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Generate random server token'
  hosts: '{{ groups.k3s_primary_masters | first }}'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_token_create'

- name: 'Bootstrap RHEL masters'
  hosts: 'k3s_masters:&rhel'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rhel_bootstrap'

- name: 'Bootstrap Void masters'
  hosts: 'k3s_masters:&void'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'void_bootstrap'

- name: 'Reboot masters and sundries'
  hosts: 'k3s_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_reboot_slow'
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'helm_install'      # not using Helm currently

- name: 'Deploy core manifests'
  hosts: '{{ groups.k3s_primary_masters | first }}'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_install'       # install system manifests (and configs)
    - 'k3s_patch'         # modify installed settings (kubectl patch)
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Bootstrap RHEL agents'
  hosts: 'k3s_agents:&rhel'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rhel_bootstrap'

- name: 'Bootstrap Void agents'
  hosts: 'k3s_agents:&void'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'void_bootstrap'

- name: 'Reboot agents and sundries'
  hosts: 'k3s_agents'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_reboot_slow'
    - 'k3s_labels_apply'

#- name: 'Install user interface'
#  hosts: 'interface'
#  gather_facts: no
#  become: yes
#  tags:
#    - 'bootstrap'
#    - 'never'
#  handlers:
#    - import_tasks: 'handlers/main.yml'
#  roles:
#    - 'interface_install'

- name: 'Fetch application manifests'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'apps_install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'apps_fetch'        # fetch app images
    - 'rolling_restart'

- name: 'Deploy application manifests'
  hosts: '{{ groups.k3s_primary_masters | first }}'
  gather_facts: no
  become: yes
  tags:
    - 'apps_install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'apps_install'      # install app manifests (and configs)
    - 'apps_patch'        # modify installed settings (kubectl patch)
    # - 'do_nothing'        # these two let me stop and start the roles
    # - 'fail_egregiously'  # these two let me stop and start the roles

- name: 'Smoke testing'
  hosts: '{{ groups.k3s_primary_masters | first }}'
  gather_facts: no
  become: no
  tags:
    - 'smoke_test'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'smoke_test'

# Badly-designed Ansible feature (argument_spec) is unusable because it forces 'always' tag :(
- name: 'Alert all consoles in the cluster'
  hosts: 'all'
  gather_facts: no
  become: no
  tags:
    - 'allwall'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'all_wall'

- name: 'Rolling restart cluster'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'rolling_restart'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'rolling_restart'

- name: 'Purge k3s cluster'
  hosts: 'all'
  gather_facts: no
  become: yes
  tags:
    - 'destroy_cluster'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_destroy_all'
...
# vim: set filetype=yaml
