---
- name: 'Install nodes'
  hosts: 'nodes'
  gather_facts: no
  become: yes
  tags:
    - 'install'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  tasks:
    - name: 'Set hostname'
      register: 'reg_hostname'
      loop:
        - '/etc/hostname'
      template:
        src: '{{ item[1:] }}.j2'
        dest: '{{ item }}'

    - name: 'Set hostname (2)'
      register: 'reg_hostname_2'
      vars:
        conf:
          rhel: 'rhel'
          void: 'openbsd' # apparently the best option for Void
      hostname:
        name: '{{ fqdn }}'
        use: '{{ conf[distro] }}'

    - name: 'Set random seed'
      notify: 'Restart sshd'
      become: yes
      vars:
        file: '/var/lib/random-seed'
      command:
        argv:
          - '/bin/dd'
          - 'bs=1'
          - 'count={{ "4 KB" | human_to_bytes }}'
          - 'if=/dev/urandom'
          - 'of={{ file }}'

    # /dev/urandom is guaranteed to return at least one byte
    # but can't guarantee more. By getting one at a time we
    # guarantee to get our full 4K.

    - name: 'Delete sshd private keys'
      notify: 'Restart sshd'
      loop:
        - 'ecdsa'
        - 'dsa'
        - 'ed25519'
        - 'rsa'
      file:
        path: '/etc/ssh/ssh_host_{{ item }}_key'
        state: 'absent'

    - meta: 'flush_handlers'

    - name: 'Reboot'
      when: 'reg_hostname is changed
             or reg_hostname_2 is changed'
      reboot:

    - name: 'Create local repo mountpoint'
      register: 'reg_mkdir'
      vars:
        e_readonly: 'Read-only file system'
      failed_when:
        - 'reg_mkdir.rc is defined'
        - 'reg_mkdir.module_stdout is defined'
        - 'reg_mkdir.rc != 0'
        - 'e_readonly not in reg_mkdir.module_stdout'
      file:
        path: '/mnt/disc'
        state: 'directory'
        mode: '0000'

    - name: 'Add local repo mount to fstab'
      lineinfile:
        path: '/etc/fstab'
        line: '/dev/sr0  /mnt/disc  iso9660  ro,noauto  0  0'

    - name: 'Mount local repo image'
      register: 'reg_mount'
      vars:
        e_notfound: "can't find in /etc/fstab."
        e_already: 'already mounted'
      changed_when:
        - 'reg_mount.rc != 0'
        - 'e_already not in reg_mount.stderr'
      failed_when:
        - 'reg_mount.rc != 0'
        - 'e_notfound in reg_mount.stderr'
      command:
        argv:
          - '/bin/mount'
          - '/mnt/disc'

    - name: 'Update xbps config'
      when: 'distro == "void"'
      loop:
        - '/etc/xbps.d/00-repository-main.conf'
      template:
        src: '{{ item[1:] }}.j2'
        dest: '{{ item }}'

    - name: 'Add repo entry to hosts file'
      when: 'distro == "void"'
      lineinfile:
        path: '/etc/hosts'
        line: '65.21.160.177 repo-default.voidlinux.org'

    # All this when-ing is a bit ugly
    - name: 'Install keepalived'
      when: 'distro == "rhel"'
      package:
        name: 'keepalived'

    # TODO: failed_when
    - name: 'Update xbps index'
      when: 'distro == "void"'
      command:
        argv:
          - '/bin/xbps-install'
          - '-Sy'

    # TODO: failed_when
    - name: 'Update xbps'
      when: 'distro == "void"'
      command:
        argv:
          - '/bin/xbps-install'
          - '-uy'
          - 'xbps'

    # TODO: failed_when
    - name: 'Install keepalived'
      when: 'distro == "void"'
      command:
        argv:
          - '/bin/xbps-install'
          - '-y'
          - 'keepalived'

    - name: 'Set up keepalived service'
      # service:
      #   name: 'keepalived'
      #   enabled: yes
      when: 'distro == "void"'
      file:
        src: '/etc/sv/keepalived'
        dest: '/var/service/keepalived'
        state: link

    - name: 'Configure keepalived'
      notify:
        - 'Restart keepalived'
      loop:
        - '/etc/keepalived/keepalived.conf'
      template:
        src: '{{ item[1:] }}.j2'
        dest: '{{ item }}'

    - name: 'Copy legacy RPMs'
      when: 'distro == "rhel"'
      loop:
        - 'iptables-libs-1.6.2-2.fc28.x86_64.rpm'
        - 'iptables-1.6.2-2.fc28.x86_64.rpm'
      copy:
        src: 'rpms/{{ item }}'
        dest: '/tmp/'

    # TODO: failed_when/changed_when
    - name: 'Install legacy RPMs'
      when: 'distro == "rhel"'
      register: 'reg_iptables'
      vars:
        legacy_rpms:
          - '/tmp/iptables-libs-1.6.2-2.fc28.x86_64.rpm'
          - '/tmp/iptables-1.6.2-2.fc28.x86_64.rpm'
        command:
          - '/bin/yum'
          - 'localinstall'
          - '--allowerasing'
          - '--nogpgcheck'
          - '-y'
      command:
        argv: '{{ command + legacy_rpms }}'

    - name: 'Set up iptables service'
      # service:
      #   name: 'iptables'
      #   enabled: yes
      when: 'distro == "void"'
      file:
        src: '/etc/sv/iptables'
        dest: '/var/service/iptables'
        state: link

    - name: 'Reboot'
      when: 'reg_iptables is changed'
      reboot:

- name: 'Bootstrap masters'
  hosts: 'k3s_masters'
  gather_facts: no
  become: yes
  tags:
    - 'bootstrap'
    - 'never'
  handlers:
    - import_tasks: 'handlers/main.yml'
  vars:
    token_file: '/etc/k3s-token-file'
    # /tmp and /var/tmp are mounted noexec so use /run
    k3s_install_script: '/home/ansible/install_k3s.sh'
  environment:
    K3S_TOKEN_FILE: '{{ token_file }}'
  tasks:
    - name: 'Create random token file'
      register: 'reg_create_token'
      copy:
        content: '{{ (now().microsecond ~ inventory_hostname) | password_hash("sha256") | b64encode }}'
        dest: '{{ token_file }}'
        force: false  # if exists, don't recreate it

    - name: 'Copy install script'
      loop:
        - '{{ k3s_install_script }}'
      copy:
        src: '{{ item[1:] }}'
        dest: '{{ item }}'
        mode: '0755'

    # The k3s project has taken the unusual decision to host built
    # binaries without any wrapper or compression at all. You just
    # download the actual binary and away you go. This is possible
    # since Go binaries famously have no dependencies.

    # This made me feel slimy and naked so I wrapped it up in a
    # tarball. It didn't even have a version number attached.
    - name: 'Unarchive the binary'
      unarchive:
        src: 'binaries/k3s-v1.28.4+k3s2.tgz'
        dest: '/usr/local/bin/'

    - name: 'Permission the binary'
      file:
        path: '/usr/local/bin/k3s'
        mode: '0755'

    # Apparently the next step also removes the binary
    - name: 'Backup the binary'
      copy:
        remote_src: yes
        src: '/usr/local/bin/k3s'
        dest: '/usr/local/bin/k3s.bak'

    # TODO: make safe with failed_when
    - name: 'Remove old data'
      register: 'reg_remove'
      vars:
        e_notfound: 'No such file or directory'
      failed_when:
        - 'reg_remove.rc > 0'
        - 'e_notfound not in reg_remove.msg'
      command: '/usr/local/bin/k3s-uninstall.sh'

    # ffs
    - name: 'Restore the backup'
      when: 'reg_remove is changed'
      copy:
        remote_src: yes
        src: '/usr/local/bin/k3s.bak'
        dest: '/usr/local/bin/k3s'

    # hmm, ends with error, api server not starting?
    - name: 'Run install script'
      environment:
        K3S_KUBECONFIG_MODE: '644'
        NO_SELINUX: 'true'
        INSTALL_K3S_SKIP_DOWNLOAD: 'true'
        INSTALL_K3S_EXEC: 'server --disable traefik --disable=servicelb --disable=traefik --flannel-backend=none --disable-network-policy --cluster-cidr=192.168.0.0/16'
      command:
        argv:
          - '{{ k3s_install_script }}'
          - '--cluster-init'
          - '--kube-apiserver-arg=feature-gates=RemoveSelfLink=false'

    - name: 'Reboot'
      reboot:
...
