---
ve_service_files:
 - file: '{{ k3s_service_dir }}/log/run'
   mode: '0755'
 - file: '{{ k3s_service_dir }}/finish'
   mode: '0755'
 - file: '{{ k3s_service_dir }}/conf'
 - file: '{{ k3s_service_dir }}/run'
   mode: '0755'
...
# vim: set filetype=yaml
