---
- name: 'Reboot primary'
  when: 'is_primary'
  reboot:
    post_reboot_delay: 30

- name: 'Reboot secondaries and agents'
  when: 'not is_primary'
  reboot:
    post_reboot_delay: 10

- name: 'Wait for system to settle'
  pause:
    prompt: |
      This might take a while. Pausing for 10 minutes.
    seconds: 600

# TODO: see what effect async and poll have on this task, maybe use it more
# TODO: figure out failed_when condition for kubectl wait
# Nodes won't go to Ready state without a CNI installed, but we can check they exist. Didn't know that was necessary.
- name: 'Wait for all nodes to exist'
  register: 'reg_nodes'
  failed_when:
    - 'reg_nodes is failed
       or fqdn not in (reg_nodes.json | json_query("items[*].metadata.name"))'
  retries: 120
  delay: 20
  until: 'reg_nodes is success'
  uri:
    url: 'https://{{ k3s_first_primary }}:6443/api/v1/nodes'
    validate_certs: no
    headers:
      Authorization: 'Bearer {{ node_token }}'
    return_content: yes
...
# vim: set filetype=yaml
