---
- name: 'Ensure manifests directory exists'
  when: 'is_primary'
  vars:
    path: '{{ (manifests_path_prefix, item) | path_join }}'
  loop: '{{ manifests }}'
  file:
    path: '{{ path | dirname }}'
    state: 'directory'

- name: 'Template in manifests'
  when: 'is_primary'
  vars:
    path: '{{ (manifests_path_prefix, item) | path_join }}'
  loop: '{{ manifests }}'
  template:
    src: '{{ path[1:] }}.j2'
    dest: '{{ path }}'

- name: 'Install manifests'
  register: 'reg_install_manifests'
  when: 'is_primary'
  vars:
    path: '{{ (manifests_path_prefix, item) | path_join }}'
  loop: '{{ manifests }}'
  failed_when:
    - 'reg_install_manifests.rc != 0'
    - 'e_manifest_already not in reg_install_manifests.stderr'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'create'
      - '-f'
      - '{{ path }}'

# do repeat-until for long waits
# TODO: failed_when
- name: 'Wait for pods'
  when:
    - 'wait_selectors is defined'
    - 'wait_selectors'
  loop: '{{ wait_selectors }}'
  run_once: yes
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'wait'
      - '--timeout={{ wait_timeout | default(default_wait_timeout) }}'
      - '--for=condition=Ready'
      - 'pod'
      - '-n'
      - '{{ namespace }}'
      - '--selector={{ item }}'
...
# vim: set filetype=yaml
