---
# If we don't do this here, nodes never show as Ready since they don't
# have a CNI (because Flannel is disabled)
- name: 'Install Calico CNI'
  vars:
    manifests: '{{ manifests["calico"] }}'
    namespace: '{{ namespaces["core"] }}'
    wait_selectors: '{{ selectors["core"] }}'
  import_tasks: 'install_and_wait.yml'

# TODO: see what effect async and poll have on this task, maybe use it more
# TODO: figure out failed_when condition for kubectl wait
- name: 'Wait for all nodes'
  run_once: yes
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'wait'
      - '--timeout={{ nodes_timeout }}'
      - '--for=condition=Ready'
      - 'node'
      - '{{ inventory_hostname }}.{{ domain }}'

# Need Longhorn before Registry
- name: 'Install Longhorn'
  vars:
    manifests: '{{ manifests["longhorn"] }}'
    namespace: '{{ namespaces["longhorn"] }}'
    wait_selectors: '{{ selectors["longhorn"] }}'
  import_tasks: 'install_and_wait.yml'

- name: 'Install registry configuration'
  blockinfile:
    block: |
      mirrors:
        docker.io:
          endpoint:
            - 'http://127.0.0.1:{{ registry_service_node_port }}'
    dest: '{{ registry_file }}'
    create: yes
    marker: '# {mark} ANSIBLE MANAGED BLOCK --- registry'

# This should be first after Calico. I'd be tempted to install before
# Calico, but I don't think that'd work.
# Might need to set up some storage.
# https://thomasdegraaff.eu/notes/2021/12/04/k3s_docker_pull_through_registry/
- name: 'Install Registry'
  vars:
    manifests: '{{ manifests["registry"] }}'
    namespace: '{{ namespaces["registry"] }}'
    wait_selectors: '{{ selectors["registry"] }}'
  import_tasks: 'install_and_wait.yml'

- name: 'Install MetalLB'
  vars:
    manifests: '{{ manifests["metallb"] }}'
    namespace: '{{ namespaces["metallb"] }}'
    wait_selectors: '{{ selectors["metallb"] }}'
  import_tasks: 'install_and_wait.yml'

- name: 'Install MetalLB pool'
  vars:
    manifests: '{{ manifests["metallb_pool"] }}'
  import_tasks: 'install_and_wait.yml'

- name: 'Install nginx ingress'
  vars:
    manifests: '{{ manifests["nginx-ingress"] }}'
  import_tasks: 'install_and_wait.yml'

- name: 'Install cert-manager'
  vars:
    manifests: '{{ manifests["cert-manager"] }}'
    namespace: '{{ namespaces["cert-manager"] }}'
    wait_selectors: '{{ selectors["cert-manager"] }}'
  import_tasks: 'install_and_wait.yml'

# Removed deletion of completed jobs. There's no reliable way to wait
# for completion --- the wait is never triggered by the condition and
# Google knows nothing.
...
# vim: set filetype=yaml
