---
certmgr_namespace: 'cert-manager'

# please use minutes so we can rely on seconds for polling
certmgr_timeout: '10m'

certmgr_version: 'v0.7.2'

certmgr_base_url: 'https://raw.githubusercontent.com/cert-manager/cert-manager/{{ certmgr_version }}'

certmgr_manifests:
  - '{{ certmgr_base_url }}/deploy/manifests/cert-manager.yaml'

certmgr_images:
  - 'quay.io/jetstack/cert-manager-cainjector:{{ certmgr_version }}'
  - 'quay.io/jetstack/cert-manager-webhook:{{ certmgr_version }}'
  - 'quay.io/jetstack/cert-manager-controller:{{ certmgr_version }}'

certmgr_selectors:
  - 'app.kubernetes.io/instance=cert-manager'
...
# vim: set filetype=yaml
