---
- name: 'Reboot'
  reboot:
    pre_reboot_delay: '{{ pre_reboot_delay_s | int }}'
    post_reboot_delay: '{{ post_reboot_delay_s | int }}'

- name: 'Wait for system to settle'
  when: 'settle_delay_s is defined'
  vars:
    delay_text: '{{ (settle_delay_s ~ "s")
                    if (settle_delay_s < 60)
                    else (((settle_delay_s / 60) | int) ~ "m") }}'
  pause:
    prompt: |
      This might take a while. Pausing for {{ delay_text }}.
    seconds: '{{ settle_delay_s | int }}'
...
# vim: set filetype=yaml
