---
- name: 'Install manifests'
  register: 'reg_install_manifests'
  loop: '{{ loop_list }}'
  loop_control:
    pause: '{{ pause_seconds }}'
  failed_when:
    - 'reg_install_manifests.rc != 0'
    - 'e_manifest_already not in reg_install_manifests.stderr'
    - 'e_manifest_namespace not in reg_install_manifests.stderr'
  command:
    argv:
      - '{{ k3s_binary_dir }}/kubectl'
      - 'create'
      - '-f'
      - '{{ manifests_path_prefix }}/{{ manifest_set.prefix }}/{{ item | basename }}'
      - '-n'
      - '{{ manifest_set.namespace }}'

# seems like the next task might be failing before the containers register as
# existing --- mitigate with a pause
- name: 'Pause a few seconds for system to settle'
  when:
    - 'reg_install_manifests is not skipped'
  pause:
    seconds: '{{ pause_seconds }}'

- name: 'Wait task'
  include_tasks:
    file: 'wait_for.yml'
...
# vim: set filetype=yaml
