---
pause_seconds: 10

manifest_sets:
  - prefix: 'postgresql'
    namespace: 'postgres-system'
    install:
      - 'postgres-combined.yaml.j2'
    config: [ ]
    post_install_selectors:
      - 'app=postgres'
      - 'service=postgres'
    post_config_selectors: [ ]

  - prefix: 'elastic'
    namespace: 'elastic-system'
    install:
      - 'elastic.yaml.j2'
      - 'kibana.yaml.j2'
    config: [ ]
    post_install_selectors: [ ]
    post_config_selectors: [ ]

  # Prometheus
  - prefix: 'prometheus'
    namespace: 'monitoring-system'
    install:
      - 'prometheus.yaml.j2'
    config: [ ]
    post_install_selectors:
      - 'app=prometheus'
      - 'service=prometheus'
    post_config_selectors: [ ]
...
# vim: set filetype=yaml
