---
nginx_images:
#  - 'k8s.gcr.io/ingress-nginx/controller:{{ nginx_version }}'
#  - 'k8s.gcr.io/ingress-nginx/controller@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de'
#  - 'docker.io/jettech/kube-webhook-certgen:{{ jettech_version }}'
...
# vim: set filetype=yaml
