---
ansible_user: 'ansible'
ansible_host: '{{ network | ipv4(ip_fourth_byte) | ipv4("address") }}'
fqdn: '{{ inventory_hostname }}.{{ domain }}'

keepalived_vip_address: '{{ network | ipv4(keepalived_vip_fourth_byte) | ipv4("address") }}'
keepalived_notify_to: 'admin@{{ domain }}'
keepalived_notify_from: '{{ inventory_hostname }}@{{ domain }}'

k3s_version: 'v1.28.4+k3s2'
k3s_sha256_checksum: '9014535a4cd20c788282d60398a06279983562093455b53ab76701539ce67acf'
...
# vim: set filetype=yaml
