---
ansible_user: 'ansible'
fqdn: '{{ inventory_hostname }}.{{ domain }}'

k3s_version: 'v1.28.4+k3s2'
k3s_tarball: '{{ playbook_dir }}/binaries/k3s-{{ k3s_version }}.tgz'
...
# vim: set filetype=yaml
