---
- name: 'Restart keepalived'
  # service:
  #   name: 'keepalived'
  #   state: 'restarted'
  command:
    argv:
      - 'sv'
      - 'restart'
      - 'keepalived'

- name: 'Restart sshd'
  become: yes
  # service:
  #   name: 'sshd'
  #   state: 'restarted'
  command:
    argv:
      - 'sv'
      - 'restart'
      - 'sshd'
...
# vim: set filetype=yaml
