---
- name: 'Restart keepalived'
  # service:
  #   name: 'keepalived'
  #   state: 'restarted'
  vars:
    service_command:
      void: 'sv'
      rhel: 'systemctl'
  command:
    argv:
      - '{{ service_command[distro] }}'
      - 'restart'
      - 'keepalived'

- name: 'Restart sshd'
  become: yes
  # service:
  #   name: 'sshd'
  #   state: 'restarted'
  vars:
    service_command:
      void: 'sv'
      rhel: 'systemctl'
  command:
    argv:
      - '{{ service_command[distro] }}'
      - 'restart'
      - 'sshd'
...
# vim: set filetype=yaml
