---
- name: 'Add local repo mount to fstab'
  lineinfile:
    path: '/etc/fstab'
    line: '/dev/sr0  /mnt/disc  iso9660  ro,noauto  0  0'

- name: 'Mount local repo image'
  register: 'reg_mount'
  vars:
    e_notfound: "can't find in /etc/fstab."
    e_already: 'already mounted'
  changed_when:
    - 'reg_mount.rc != 0'
    - 'e_already not in reg_mount.stderr'
  failed_when:
    - 'reg_mount.rc != 0'
    - 'e_notfound in reg_mount.stderr'
  command:
    argv:
      - '/bin/mount'
      - '/mnt/disc'

# TODO: add yum config
...
# vim: set filetype=yaml
