---
- name: 'Create emissary namespace'
  register: 'reg_ns'
  run_once: yes
  failed_when:
    - 'reg_ns.rc > 0'
    - 'e_ns_already not in reg_ns.stderr'
  command: '{{ k3s_binary_dir }}/kubectl create namespace emissary'
...
# vim: set filetype=yaml
