---
# If you use this after k3s service is installed and up, you will need
# a service restart or node reboot to get the images loaded.

- name: 'Loop over images'
  vars:
    tarfile: '{{ item.split(":") | first | replace("/", "_") | replace("@", "_") }}.tar'
  loop: '{{ images }}'
  include_tasks:
    file: 'loop.yml'
...
# vim: set filetype=yaml
