---
all_hosts_records: '{{ groups.all }}'

sysctl_settings:
  - 'net.bridge.bridge-nf-call-iptables = 1'
  - 'net.bridge.bridge-nf-call-ip6tables = 1'
  - 'net.ipv4.ip_forward = 1'
  - 'net.ipv6.conf.all.disable_ipv6 = 1'
  - 'net.ipv6.conf.default.disable_ipv6 = 1'

config_templates:
  - '/etc/machine-id'
  - '/etc/hostname'

k3s_logrotate_configs:
  - '/etc/logrotate.d/standard'
  - '/etc/logrotate.d/k3s'

bootstrap_templates:
  - '/etc/environment'

sshd_private_key_types:
  - 'ecdsa'
  - 'dsa'
  - 'ed25519'
  - 'rsa'

# preferred shell first
k3s_shells:
  - '/usr/bin/tmux'
  - '/sbin/bash'

k3s_chsh: '/usr/bin/chsh'
...
# vim: set filetype=yaml
