---
- name: 'Add gateway'
  lineinfile:
    path: '/etc/sysconfig/network'
    line: 'GATEWAY={{ network_gateway }}'
    insertbefore: 'EOF'

- name: 'Add local repo mount to fstab'
  lineinfile:
    path: '/etc/fstab'
    line: '{{ fstab_device }}  {{ fstab_mount }}  iso9660  ro,noauto  0  0'

- name: 'Mount local repo image'
  register: 'reg_mount'
  changed_when:
    - 'reg_mount.rc != 0'
    - 'e_mount_already_already not in reg_mount.stderr'
    - 'e_mount_no_media not in reg_mount.stderr'
  failed_when:
    - 'reg_mount.rc != 0'
    - 'e_mount_notfound_fstab in reg_mount.stderr'
    - 'e_mount_no_media not in reg_mount.stderr'
  command:
    argv:
      - '/bin/mount'
      - '{{ fstab_mount }}'

- name: 'Install yum repos'
  loop: '{{ yum_repos }}'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

# TODO: maybe replace with yum module?
# TODO: figure out failed_when for yum clean all and yum update
- name: 'Freshen yum data'
  when:
    - 'e_mount_no_media not in reg_mount.stderr'
  loop:
    - 'clean all'
    - '-y update'
  command: 'yum {{ item }}'

- name: 'Copy legacy RPMs'
  loop: '{{ legacy_rpms }}'
  copy:
    src: 'rpms/{{ item }}'
    dest: '/tmp/'

# TODO: figure out failed_when for yum install and changed_when so we don't reboot every time
- name: 'Install legacy RPMs'
  register: 'reg_iptables'
  command:
    argv: '{{ install_command_prefix + prefixed_legacy_rpms }}'

- name: 'Reboot'
  when: 'reg_iptables is changed'
  reboot:
...
# vim: set filetype=yaml
