---
- name: 'Add gateway'
  lineinfile:
    path: '/etc/sysconfig/network'
    line: 'GATEWAY={{ network_gateway }}'
    insertbefore: 'EOF'

- name: 'Add local repo mount to fstab'
  lineinfile:
    path: '/etc/fstab'
    line: '{{ fstab_device }}  {{ fstab_mount }}  iso9660  ro,noauto  0  0'

- name: 'Mount local repo image'
  register: 'reg_mount'
  changed_when:
    - 'reg_mount.rc != 0'
    - 'e_mount_already not in reg_mount.stderr'
  failed_when:
    - 'reg_mount.rc != 0'
    - 'e_mount_notfound in reg_mount.stderr'
  command:
    argv:
      - '/bin/mount'
      - '{{ fstab_mount }}'

# TODO: add yum config
# sudo install /mnt/disc/media.repo /etc/yum.repos.d/ -m0644
# change title to AppStream
# add lines:
#enabled=1
#baseurl=file:///mnt/disc/AppStream
#gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
# Set gpgcheck to 1
# Duplicate and change AppStream to BaseOS wherever you see it
# sudo yum clean all
# sudo yum updates

- name: 'Copy legacy RPMs'
  loop:
    - 'clean all'
    - 'update'
  command: 'yum {{ item }}'

- name: 'Copy legacy RPMs'
  loop: '{{ legacy_rpms }}'
  copy:
    src: 'rpms/{{ item }}'
    dest: '/tmp/'

# TODO: failed_when/changed_when
- name: 'Install legacy RPMs'
  register: 'reg_iptables'
  command:
    argv: '{{ install_command_prefix + prefixed_legacy_rpms }}'

- name: 'Reboot'
  when: 'reg_iptables is changed'
  reboot:
...
# vim: set filetype=yaml
