---
- name: 'Create service tree'
  file:
    path: '{{ k3s_service_dir }}/log'
    state: 'directory'

- name: 'Template in runit service'
  loop: '{{ ve_service_files }}'
  template:
    src: '{{ item.file[1:] }}.j2'
    dest: '{{ item.file }}'
    mode: '{{ item.mode | default("0644") }}'

- name: 'Enable service'
  file:
    src: '{{ k3s_service_dir }}'
    dest: '/var/service/{{ k3s_service_dir | basename }}'
    state: 'link'
...
# vim: set filetype=yaml
