---
# /etc/rancher/k3s/k3s.yaml ?

- name: 'Disable swap'
  replace:
    path: '/etc/fstab'
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: 'Create nodename directory'
  file:
    path: '{{ nodename_file | dirname }}'
    state: 'directory'

- name: 'Create iscsi initiator name'
  register: 'reg_iname'
  command:
    argv:
      - '/usr/bin/iscsi-iname'

- name: 'Template in iscsi configs'
  loop:
    - '/etc/iscsi/initiatorname.iscsi'
    - '/etc/iscsi/iscsid.conf'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'

- name: 'Copy hostname to nodename'
  copy:
    remote_src: yes
    src: '/etc/hostname'
    dest: '{{ nodename_file }}'

# Force local image use
- name: 'Disable fetching from docker.io'
  loop:
    - '0.0.0.0 docker.io'
    - '0.0.0.0 registry-1.docker.io registry-1'
  lineinfile:
    line: '{{ item }}'
    insertafter: 'EOF'
    path: '/etc/hosts'

- name: 'Ensure images directory exists'
  file:
    state: 'directory'
    path: '/var/lib/rancher/k3s/agent/images'
...
# vim: set filetype=yaml
