---
# /etc/rancher/k3s/k3s.yaml ?

- name: 'Disable swap'
  replace:
    path: '/etc/fstab'
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: 'Create directories'
  loop: '{{ k3s_data_dirs }}'
  file:
    path: '{{ item }}'
    state: 'directory'

- name: 'Create iscsi initiator name'
  register: 'reg_iname'
  command:
    argv:
      - '{{ iscsi_iname_command[distro] }}'

- name: 'Template in configs'
  loop:
    - '/etc/iscsi/initiatorname.iscsi'
    - '/etc/iscsi/iscsid.conf'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'

# TODO: replace with a script?
- name: 'Generate bash completions'
  shell: 'kubectl completion bash | sudo tee /etc/profile.d/bbsh_completion_kubectl.sh'

- name: 'Copy hostname to nodename'
  copy:
    remote_src: yes
    src: '/etc/hostname'
    dest: '{{ nodename_file }}'

# Force local image use
- name: 'Disable fetching from docker.io'
  loop:
    - '0.0.0.0 docker.io'
    - '0.0.0.0 registry-1.docker.io registry-1'
  lineinfile:
    line: '{{ item }}'
    insertafter: 'EOF'
    path: '/etc/hosts'
...
# vim: set filetype=yaml
