---
# Inverted failed_when :)
- name: 'Commit all snapshots'
  register: 'reg_delete_snapshot'
  vars:
    e_ok: 'deleted'
    e_notfound: 'the domain does not have a current snapshot'
    #e_file: 'No such file or directory'
    cmd:
      - 'scripts/snapshot_commit.bash'
      - '{{ fqdn | quote }}'
  retries: 10
  until: 'reg_delete_snapshot is success'
  changed_when: no
  failed_when:
    - 'reg_delete_snapshot.rc == 0'
    - 'e_ok in reg_delete_snapshot.stdout'
    - 'e_notfound not in reg_delete_snapshot.stderr'
  args:
    executable: '/bin/bash'
  script: '{{ cmd | join(" ") }}'

- name: 'Create a snapshot image'
  vars:
    cmd:
      - 'scripts/snapshot_take.bash'
      - '{{ fqdn | quote }}'
      - '{{ snapshot_name | default("snapshot") | quote }}'
  args:
    executable: '/bin/bash'
  script: '{{ cmd | join(" ") }}'

# needs module? :/ 
...
# vim: set filetype=yaml
