---
calico_namespace: 'kube-system'

# please use minutes so we can rely on seconds for polling
calico_timeout: '20m'
nodes_timeout: '20m'

calico_version: 'v3.27.2'
tigera_version: 'v1.32.5'

calico_base_url: 'https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests'

calico_manifests:
  - '{{ calico_base_url }}/calico.yaml'
  - '{{ calico_base_url }}/calicoctl.yaml'
  - '{{ calico_base_url }}/tigera-operator.yaml'
  - '{{ calico_base_url }}/custom-resources.yaml'

calico_images:
  - 'calico/ctl:{{ calico_version }}'
  - 'docker.io/calico/cni:{{ calico_version }}'
  - 'docker.io/calico/node:{{ calico_version }}'
  - 'docker.io/calico/kube-controllers:{{ calico_version }}'
  - 'quay.io/tigera/operator:{{ tigera_version }}'

core_selectors:
  - 'k8s-app=kube-dns'
  - 'k8s-app=metrics-server'
  - 'app=local-path-provisioner'

calico_selectors:
  - 'k8s-app=calico-kube-controllers'
  - 'k8s-app=calico-node'
...
# vim: set filetype=yaml
