---
- name: 'Create empty iptables settings file'
  copy:
    remote_src: yes
    src: '/etc/iptables/empty.rules'
    dest: '/etc/iptables/iptables.rules'

- name: 'Prevent service start'
  register: 'reg_prevent_start'
  failed_when:
    - 'reg_prevent_start is failed'
    - 'e_touch_fail not in reg_prevent_start.msg'
  file:
    state: 'touch'
    path: '/etc/sv/k3s/down'
    owner: 'root'
    group: 'root'
    mode: '0444'

- name: 'Stop service'
  file:
    path: '/var/service/k3s'
    state: 'absent'

- name: 'Wait a sec'
  pause:
    seconds: 3

- name: 'Uninstall service'
  file:
    path: '/etc/sv/k3s'
    state: 'absent'
...
# vim: set filetype=yaml
