---
k3s_logrotate_configs:
  - '/etc/logrotate.d/standard'
  - '/etc/logrotate.d/k3s'

# preferred shell first
k3s_shells:
  - '/usr/bin/tmux'
  - '/sbin/bash'

k3s_chsh: '/usr/bin/chsh'
...
# vim: set filetype=yaml
