---
patches:
  - name: 'kubernetes-dashboard'
    path: 'dashboard-service.yaml.j2'
    type: 'service'
    prefix: 'dashboard'
    namespace: 'kubernetes-dashboard'

  - name: 'kubernetes-dashboard'
    path: 'dashboard-deployment.yaml.j2'
    type: 'deployment.apps'
    prefix: 'dashboard'
    namespace: 'kubernetes-dashboard'

#  - name: 'longhorn-storageclass'
#    path: 'longhorn_sc.yaml.j2'
#    type: 'configmap'
#    prefix: 'longhorn'
#    namespace: 'longhorn-system'
#
#  - name: 'cert-manager-cainjector'
#    path: 'reps_3.yaml.j2'
#    type: 'deployment'
#    prefix: 'kube-system'
#    namespace: 'cert-manager'
...
# vim: set filetype=yaml
