---
dependencies:
  - vars:
      packages:
# commented packages not available in RHEL disc but needed for Void.
#        - 'nghttp2'
#        - 'libssh2'
        - 'bind-utils'
        - 'icu'
        - 'libstdc++'
#        - 'the_silver_searcher'  # ok, not so much needed as liked ;)
        - 'cronie'
        - 'chrony'
#        - 'open-iscsi'
        - 'tmux'
        - 'logrotate'
    role: 'meta_package_install'
  - vars:
      services:
        - 'chronyd'
        - 'cronie'
        - 'iscsid'
    role: 'meta_service_enable'
...
# vim: set filetype=yaml
