---
- name: 'Write random token'
  vars:
    seed: '{{ inventory_hostname ~ now().microsecond }}'
  copy:
    content: '{{ lookup("password", random_spec, seed=seed)
                 | password_hash("sha256")
                 | b64encode }}'
    dest: '{{ random_token_file }}'
    mode: '0400'
    owner: 'root'
    group: 'root'

- name: 'Generate server token from random token'
  failed_when: no  # TODO, figure out fail conditions
  async: '{{ token_timeout | int }}'
  poll: 0
  command:
    argv:
      - '{{ k3s_binary }}'
      - 'server'
      - '--token-file'
      - '{{ random_token_file }}'

- name: 'Wait for file to exist'
  wait_for:
    delay: 1  # give it a second
    path: '{{ actual_token_file }}'
    timeout: '{{ token_timeout | int }}'

- name: 'End the token generation process'
  failed_when: no  # TODO, figure out fail conditions
  command:
    argv:
      - '/bin/pkill'
      - '{{ k3s_binary | basename }}'
...
# vim: set filetype=yaml
