---
- name: 'Generate random token'
  vars:
    spec: '/dev/null chars=ascii_letters,digits length=64'
    seed: '{{ inventory_hostname ~ now().microsecond }}'
  set_fact:
    random_token: '{{ lookup("password", spec, seed=seed)
                      | password_hash("sha256")
                      | b64encode }}'

- name: 'Write random token'
  copy:
    content: '{{ random_token }}'
    dest: '{{ random_token_file }}'
    mode: '0400'  # hmm?

- name: 'Generate server token from random token'
  failed_when: no  # TODO, figure out fail conditions
  async: 120
  poll: 0
  command:
    argv:
      - '/usr/local/bin/k3s'
      - 'server'
      - '--token-file'
      - '{{ random_token_file }}'

- name: 'Wait for file to exist'
  wait_for:
    delay: 1  # give it a second
    path: '/var/lib/rancher/k3s/server/token'
    timeout: 120

- name: 'End the token generation process'
  failed_when: no  # TODO, figure out fail conditions
  command:
    argv:
      - '/bin/pkill'
      - 'k3s'
...
# vim: set filetype=yaml
