---
# TODO: see what effect async and poll have on this task, maybe use
# it more
# Nodes won't go to Ready state without a CNI installed, but we can
# check they exist. Didn't know that was necessary.
# Wait for node without using the API, because that requires tokens
# which don't exist yet
- name: 'Wait for all nodes to exist'
  register: 'reg_nodes'
  retries: 100
  delay: 20
  until:
    - 'reg_nodes is success'
  delegate_to: '{{ k3s_first_primary }}'
  vars:
    cmd:
      - 'scripts/node_wait_tokenless.bash'
      - '{{ fqdn }}'
  args:
    executable: '/bin/bash'
  script: '{{ cmd | join(" ") }}'
...
# vim: set filetype=yaml
