---
- name: 'debug'
  hosts: 'nodes'
  gather_facts: no
  become: no
  tasks:
    - name: 'debug'
      command: 'hostname'

- name: 'Cease all hosts'
  hosts: 'nodes'
  gather_facts: no
  become: no
  tasks:
    - name: 'List running guests'
      register: 'pre_shutdown_status'
      delegate_to: '{{ hypervisor_host }}'
      virt:
        command: 'list_vms'
        state: 'running'
        uri: 'qemu:///session'

    - name: 'Shutdown running guests'
      when: 'fqdn in pre_shutdown_status.list_vms'
      delegate_to: '{{ hypervisor_host }}'
      virt:
        name: '{{ fqdn }}'
        state: 'shutdown'
        uri: 'qemu:///session'

    - name: 'Pause for hosts to settle'
      when: 'fqdn in pre_shutdown_status.list_vms'
      delegate_to: '{{ hypervisor_host }}'
      loop_control:
        label: 'Pausing'
      pause:
        seconds: '{{ shutdown_post_delay }}'
...
# vim: set filetype=yaml
