---
metallb_namespace: 'metallb-system'

metallb_version: 'v0.14.0'

metallb_base_url: 'https://raw.githubusercontent.com/metallb/metallb-operator/{{ metallb_version }}'

metallb_manifests:
  - '{{ metallb_base_url }}/bin/metallb-operator.yaml'

metallb_images:
  - 'quay.io/metallb/metallb-operator:{{ metallb_version }}'
  - 'quay.io/metallb/controller:{{ metallb_version }}'  # v0.14.3 ?

metallb_selectors:
  - 'component=controller'
  - 'component=speaker'
...
# vim: set filetype=yaml
