---
metallb_namespace: 'metallb-system'

metallb_mode: 'manifest'

metallb_base_url: 'https://raw.githubusercontent.com/metallb'

metallb_data:
  manifest:
    base_url: '{{ metallb_base_url }}/metallb'
    path: 'config/manifests/metallb-native.yaml'
    selectors:
      - 'component=controller'
      - 'component=speaker'
  operator:
    base_url: '{{ metallb_base_url }}/metallb-operator'
    path: 'bin/metallb-operator.yaml'
    selectors:
      - 'control-plane=controller-manager'
      - 'component=webhook-server'

metallb_manifest_parts:
  - '{{ metallb_data[metallb_mode].base_url }}'
  - '{{ metallb_version }}'
  - '{{ metallb_data[metallb_mode].path }}'

metallb_manifests:
  - '{{ metallb_manifest_parts | path_join }}'

metallb_selectors: '{{ metallb_data[metallb_mode].selectors }}'
...
# vim: set filetype=yaml
