---
- name: 'Roll back to latest snapshot'
  vars:
    cmd:
      - 'scripts/snapshot_rollback.bash'
      - '{{ fqdn | quote }}'
  script: '{{ cmd | join(" ") }}'

# Synchronise ship clock with nearest Federation starbase
# after time travel
- name: 'Reset clock'
  delegate_to: '{{ inventory_hostname }}'
  connection: 'ssh'  # run remotely as 'ansible' user
  become: yes
  vars:
    cmd:
      - 'scripts/time_correct.bash'
  # sometimes tries 'sh' and fails if we don't specify
  # ah, because root user shell is 'sh' not 'bash'
  args:
    executable: '/bin/bash'
  script: '{{ cmd | join(" ") }}'

# Don't restart k3s --- might not be installed yet
...
# vim: set filetype=yaml
