---
registry_namespace: 'docker-registry'

registry_pvc_name: 'docker-registry-pvc'
registry_pvc_size_gb: 5
registry_pvc_storage_class_name: 'managed-nfs-storage'

registry_service_name: 'docker-registry'
registry_service_node_port: 30555

registry_app_name: 'docker-registry'

registry_deployment_name: 'docker-registry'

registry_container_name: 'docker-registry'

registry_container_image_version: '2.7.1'
registry_container_image: 'thomasdegraaff/registry-pull-through:{{ registry_container_image_version }}'

registry_container_user: ''
registry_container_pwd: ''

registry_volume_mount_path: '/var/lib/registry'
registry_volume_name: 'docker-registry-data'
...
# vim: set filetype=yaml
