---
- name: 'Configure for RHEL'
  when: 'distro == "rhel"'
  import_tasks: 'rhel_configure.yml'

- name: 'Configure for Void'
  when: 'distro == "void"'
  import_tasks: 'void_configure.yml'

- name: 'Enable sysctl settings'
  loop: '{{ sysctl_settings }}'
  lineinfile:
    path: '/etc/sysctl.conf'
    line: '{{ item }}'
    insertafter: 'EOF'

# /etc/rancher/k3s/k3s.yaml ?

# TODO: fix this (issue #31)
- name: 'Add rshared option to root partition'
  vars:
    replace_internal: '\2,rshared'
    regex_negative_lookahead: 'rshared'
    regex_prefix: '([^ ]* \/ [^ ]* )'
    regex_suffix: '( \d \d)'
  replace:
    path: '/etc/fstab'
    regexp: '^{{ regex_prefix }}((:?(?!{{ regex_negative_lookahead }}).)*?){{ regex_suffix }}$'
    replace: '\1{{ replace_internal }}\4'

- name: 'Create local repo mountpoint'
  register: 'reg_mkdir'
  vars:
  failed_when:
    - 'reg_mkdir.rc is defined'
    - 'reg_mkdir.module_stdout is defined'
    - 'reg_mkdir.rc != 0'
    - 'e_mkdir_readonly not in reg_mkdir.module_stdout'
  file:
    path: '/mnt/disc'
    state: 'directory'
    mode: '0000'

- name: 'Template in some configs'
  loop: '{{ config_templates }}'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'

- name: 'Set random seed'
  notify: 'Restart sshd'
  command:
    argv:
      - '/bin/dd'
      - 'bs=1'
      - 'count={{ "4 KB" | human_to_bytes }}'
      - 'if=/dev/urandom'
      - 'of=/var/lib/random-seed'

# /dev/urandom is guaranteed to return at least one byte
# but can't guarantee more. By getting one at a time we
# guarantee to get our full 4K.

# need the handler; the reboot alone reliably doesn't work on one host in twelve. wtf?
- name: 'Delete sshd private keys'
  notify: 'Restart sshd'
  loop: '{{ sshd_private_key_types }}'
  file:
    path: '/etc/ssh/ssh_host_{{ item }}_key'
    state: 'absent'

- meta: 'flush_handlers'

- name: 'Reboot'
  reboot:

- name: 'Get list of base images'
  register: 'reg_base_images'
  connection: 'local'
  run_once: yes
  become: no
  retries: 5
  delay: 5
  until: 'reg_base_images is success'
  uri:
    url: 'https://raw.githubusercontent.com/k3s-io/k3s/{{ k3s_version }}/scripts/airgap/image-list.txt'
    return_content: true

- name: 'Record list of base images'
  run_once: yes
  set_fact:
    k3s_base_images_list: '{{ reg_base_images.content }}'
...
# vim: set filetype=yaml
