---
- name: 'Delete unneeded services'
  loop: '{{ unneeded_services }}'
  file:
    path: '/var/service/{{ item }}'
    state: 'absent'

- name: 'Remove some filesystem paths'
  loop: '{{ unneeded_paths }}'
  file:
    path: '{{ item }}'
    state: 'absent'

- name: 'Create empty iptables settings file'
  copy:
    remote_src: yes
    src: '/etc/iptables/empty.rules'
    dest: '/etc/iptables/iptables.rules'

- name: 'Enable iptables service'
  file:
    state: 'link'
    src: '/etc/sv/iptables'
    dest: '/var/service/iptables'

- name: 'Add DNS resolver in dhcpcd'
  vars:
    replace_internal: '8.8.8.8 \1'
    regex_negative_lookahead: '8\.8\.8\.8'
    regex_prefix: '[ \t]+static domain_name_servers='
    regex_suffix: ''
  replace:
    path: '/etc/dhcpcd.conf'
    regexp: '^{{ regex_prefix }}((:?(?!{{ regex_negative_lookahead }}).)*?){{ regex_suffix }}$'
    replace: '{{ regex_prefix }}{{ replace_internal }}{{ regex_suffix }}'
...
# vim: set filetype=yaml
