---
- name: 'Delete unneeded services'
  loop:
    - 'agetty-hvc0'
    - 'agetty-hvsi0'
    - 'agetty-tty4'
    - 'agetty-tty5'
    - 'agetty-tty6'
    - 'agetty-ttyAMA0'
    - 'agetty-ttyUSB0'
    - 'wpa_supplicant'
  file:
    path: '/var/service/{{ item }}'
    state: 'absent'

- name: 'Remove some filesystem paths'
  loop:
    - '/etc/k3s-token'
    - '/etc/k3s-token-file'
    - '/etc/issue.new-0.140_8'
    - '/etc/rc.conf.new-20210314_1'
    - '/etc/cni/net.d'
    - '/etc/myname'
    - '/etc/rancher'
    - '/etc/sudoers.new-1.9.5p2_2'
    - '/usr/libexec/kubernetes'
    - '/usr/lib/virt-sysprep'
    - '/home/ansible/install_k3s.sh'
    - '/home/ansible/k3s'
    - '/var/lib/calico'
    - '/var/lib/rancher'
    - '/var/run/containerd'
  file:
    path: '{{ item }}'
    state: 'absent'

- name: 'Create empty iptables settings file'
  copy:
    remote_src: yes
    src: '/etc/iptables/empty.rules'
    dest: '/etc/iptables/iptables.rules'

- name: 'Enable iptables service'
  file:
    state: 'link'
    src: '/etc/sv/iptables'
    dest: '/var/service/iptables'

- name: 'Add DNS resolver'
  vars:
    replace_internal: '8.8.8.8 \1'
    regex_negative_lookahead: '8\.8\.8\.8'
    regex_prefix: '[ \t]+static domain_name_servers='
    regex_suffix: ''
  replace:
    path: '/etc/dhcpcd.conf'
    regexp: '^{{ regex_prefix }}((:?(?!{{ regex_negative_lookahead }}).)*?){{ regex_suffix }}$'
    replace: '{{ regex_prefix }}{{ replace_internal }}{{ regex_suffix }}'
...
# vim: set filetype=yaml
