---
- name: 'Template in systemd service'
  loop: '{{ re_service_files }}'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    mode: '0644'

- name: 'Start service'
  systemd:
    name: 'k3s'
    enabled: yes
    daemon_reload: yes
...
# vim: set filetype=yaml
