---
# The k3s project has taken the unusual decision to host built
# binaries without any wrapper or compression at all. You just
# download the actual binary and away you go. This is possible
# since Go binaries famously have no dependencies.

# This made me feel slimy and naked so I wrapped it up in a
# tarball. It didn't even have a version number attached.

- name: 'Unarchive the k3s binary'
  unarchive:
    src: '{{ k3s_tarball }}'
    dest: '{{ k3s_binary_dir }}/'

- name: 'Permission the binary'
  file:
    path: '{{ k3s_binary_dir }}/k3s'
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: 'Add shell to /etc/shells'
  loop: '{{ k3s_shells}}'
  lineinfile:
    path: '/etc/shells'
    line: '{{ item }}'
    insertafter: 'EOF'

# TODO: figure out failed_when for chsh
- name: 'Change ansible user shell'
  command:
    argv:
      - '{{ k3s_chsh }}'
      - '-s'
      - '{{ k3s_shells | first }}'
      - 'ansible'

- name: 'Write tmux config'
  loop:
    - '/home/ansible/.tmux.conf'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    owner: 'ansible'
    group: 'ansible'
    mode: '0644'

- name: 'Create logrotate directory'
  file:
    path: '/etc/logrotate.d'
    state: 'directory'

- name: 'Template in logrotate config'
  loop: '{{ k3s_logrotate_configs }}'
  template:
    src: '{{ item[1:] }}.j2'
    dest: '{{ item }}'
    mode: '0644'

- name: 'Set cron job for logrotate'
  cron_legacy:
    name: 'Logrotate'
    cron_file: '/etc/crontab'
    user: 'root'
    job: '/usr/bin/logrotate /etc/logrotate.conf'
    minute: '04'

#    for XTABLES in iptables ip6tables; do
#        if has_working_xtables ${XTABLES}; then
#            $SUDO ${XTABLES}-save 2>/dev/null | grep -v KUBE- | grep -iv flannel | grep -iv cali | $SUDO ${XTABLES}-restore
#        fi
#    done

- name: 'Disable SELinux'
  register: 'reg_selinux'
  failed_when:
    - 'reg_selinux.rc != 0'
    - 'e_selinux_notexists not in reg_selinux.msg'
  replace:
    path: '/etc/selinux/config'
    regexp: '^SELINUX=enforcing$'
    replace: 'SELINUX=disabled'

- name: 'Disable swap'
  replace:
    path: '/etc/fstab'
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: 'Create nodename directory'
  file:
    path: '{{ nodename_file | dirname }}'
    state: 'directory'

- name: 'Copy hostname to nodename'
  copy:
    remote_src: yes
    src: '/etc/hostname'
    dest: '{{ nodename_file }}'
...
# vim: set filetype=yaml
