---
local_path_storage_class: 'local-path-storage'
longhorn_storage_class: 'longhorn'
registry_pvc_storage_class: '{{ longhorn_storage_class }}'
registry_volume_mount_path: '/var/lib/registry'

k3s_symlinks:
  - 'kubectl'
  - 'crictl'
  - 'ctr'

config_dir: '/etc/rancher/k3s'
calico_dir: '/var/lib/calico'

k3s_data_dirs:
  - '{{ config_dir }}'
  - '{{ calico_dir }}'
  - '/var/lib/rancher/k3s/server'

k3s_token_file: '/var/lib/rancher/k3s/server/token'

k3s_binary_dir: '/usr/local/bin'
k3s_binary: '{{ k3s_binary_dir }}/k3s'

k3s_scripts:
  - '{{ k3s_binary_dir }}/k3s-killall.sh'
  - '{{ k3s_binary_dir }}/k3s-uninstall.sh'

nodename_file: '{{ calico_dir }}/nodename'
environment_file: '{{ config_dir }}/k3s.env'

calico_version: 'v3.27.2'
tigera_version: 'v1.32.5'
longhorn_version: 'v1.5.3'
metallb_version: 'v0.14.0'
nginx_version: 'v0.41.2'
jettech_version: 'v1.5.0'  # ?
certmgr_version: 'v1.14.3'
...
# vim: set filetype=yaml
