---
local_path_storage_class: 'local-path-storage'
longhorn_storage_class: 'longhorn'
registry_pvc_storage_class: '{{ longhorn_storage_class }}'
registry_volume_mount_path: '/var/lib/registry'

nodes_timeout: '20m'

k3s_symlinks:
  - 'kubectl'
  - 'crictl'
  - 'ctr'

config_dir: '/etc/rancher/k3s'
calico_dir: '/var/lib/calico'

k3s_data_dirs:
  - '{{ config_dir }}'
  - '{{ calico_dir }}'
  - '/var/lib/rancher/k3s/server'

k3s_token_file: '/var/lib/rancher/k3s/server/token'

k3s_binary_dir: '/usr/local/bin'
k3s_binary: '{{ k3s_binary_dir }}/k3s'

k3s_scripts:
  - '{{ k3s_binary_dir }}/k3s-killall.sh'
  - '{{ k3s_binary_dir }}/k3s-uninstall.sh'

nodename_file: '{{ calico_dir }}/nodename'
environment_file: '{{ config_dir }}/k3s.env'

calico_version: 'v3.27.2'
tigera_version: 'v1.32.5'
longhorn_version: 'v1.5.3'
metallb_version: 'v0.13.9'
nginx_version: 'v3.4.3'
jettech_version: 'v1.5.0'  # ?
certmgr_version: 'v1.14.3'
emissary_version: '3.9.1'

postgresql_version: '16.2'
postgresql_port: 5432
postgresql_user: 'myuser'
postgresql_database: 'db0'
postgresql_replicas: 3
postgresql_disk_size_gb: 5

postgresql_secret_b64: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  363731313562393033353965306630336534636139343962393431626238613335386
  133616138313531363461376265636230613634623764316362663138610a34663265
  396662383439616439333563383533373835366138393161663138613436353931303
  9623030393465623366376533386461663961373263373634340a6139643466313737
  343932633062333332303934323462346638353661616439

postgresql_data_path: '/var/lib/postgresql/data'
postgresql_storage_class: 'local-path'

elasticsearch_version: '7.2.0'
elasticsearch_disk_size_gb: '10'

# LoadBalancer IP address fourth bytes go here
longhorn_ui_fourth_byte: '30'
postgresql_fourth_byte: '40'
elasticsearch_fourth_byte: '50'
...
# vim: set filetype=yaml
