---
pause_seconds: 10

nodes_timeout: '20m'

default_selector_type: 'pod'
default_want_condition: 'Ready'

config_dir: '/etc/rancher/k3s'
environment_file: '{{ config_dir }}/k3s.env'

k3s_first_primary: '{{ groups.k3s_primary_masters | first }}'

k3s_symlinks:
  - 'kubectl'
  - 'crictl'
  - 'ctr'

k3s_data_dirs:
  - '{{ config_dir }}'
  - '{{ calico_dir }}'
  - '{{ k3s_config_dir }}/server'
  - '{{ nodename_file | dirname }}'
  - '{{ k3s_config_dir }}/agent/images'
  - '/etc/iscsi'

k3s_config_dir: '/var/lib/rancher/k3s'
k3s_token_file: '{{ k3s_config_dir }}/server/token'
k3s_binary_dir: '/usr/local/bin'
k3s_binary: '{{ k3s_binary_dir }}/k3s'

k3s_scripts:
  - '{{ k3s_binary_dir }}/k3s-killall.sh'
  - '{{ k3s_binary_dir }}/k3s-uninstall.sh'

kube_metrics_reader_name: 'metrics-reader'

# TODO: generate and apply in service? or use dns name? put into DNS? hosts file? To think about. Yeah, probably easiest to put this into the name system once and then not need to worry about it. Assuming the same IP is assigned at every cluster start, of course.
kube_metrics_address: '10.43.75.46'  # clusterIP of "metrics-server" # home: 10.43.10.60
...
# vim: set filetype=yaml
