---
# a bit void specific?
- name: 'Create empty iptables settings file'
  copy:
    remote_src: yes
    src: '/etc/iptables/empty.rules'
    dest: '/etc/iptables/iptables.rules'

- name: 'Blank hosts file'
  copy:
    content: |
      127.0.0.1 localhost.localdomain localhost
      ::1 localhost.localdomain localhost ip6-localhost
    dest: '/etc/hosts'

# fatal: [rancher-admin]: FAILED! => {"changed": false, "msg": "Error, could not touch target: [Errno 2] No such file or directory: b'/etc/sv/k3s/down'", "path": "/etc/sv/k3s/down"}
# ...ignoring
- name: 'Prevent service start'
  file:
    state: 'touch'
    path: '/etc/sv/k3s/down'
    owner: 'root'
    group: 'root'
    mode: '0444'

- name: 'Stop service'
  failed_when: no
  #runit:
  #  name: 'k3s'
  #  state: 'stopped'
  command:
    argv:
      - '/usr/bin/sv'
      - 'down'
      - 'k3s'

- name: 'Uninstall service'
  file:
    path: '/etc/sv/k3s'
    state: 'absent'

- name: 'Reboot'
  reboot:

- name: 'Unmount kubelet'
  register: 'reg_unmount'
  become: yes
  failed_when:
    - 'reg_unmount.rc != 0'
    - 'e_notfound not in reg_unmount.stderr'
    - 'e_already not in reg_unmount.stderr'
  vars:
    e_notfound: 'no mount point specified'  # crappy inaccurate error
    e_already: 'not mounted'
  command:
    argv:
      - '/usr/bin/umount'
      - '/var/lib/kubelet'

- name: 'Remove existing configuration'
  loop: '{{ k3s_clobber_files + k3s_clobber_os_files[distro] }}'
  file:
    path: '{{ item }}'
    state: 'absent'

- name: 'Reboot'
  reboot:
...
# vim: set filetype=yaml
