---
- name: 'Create empty iptables settings file'
  copy:
    remote_src: yes
    src: '/etc/iptables/empty.rules'
    dest: '/etc/iptables/iptables.rules'

- name: 'Prevent service start'
  register: 'reg_prevent_start'
  vars:
    e_fail: 'could not touch target'
  failed_when:
    - 'reg_prevent_start is failed'
    - 'e_fail not in reg_prevent_start.msg'
  file:
    state: 'touch'
    path: '/etc/sv/k3s/down'
    owner: 'root'
    group: 'root'
    mode: '0444'

- name: 'Stop service'
  failed_when: no
  #runit:
  #  name: 'k3s'
  #  state: 'stopped'
  command:
    argv:
      - '/usr/bin/sv'
      - 'down'
      - 'k3s'

- name: 'Uninstall service'
  file:
    path: '/etc/sv/k3s'
    state: 'absent'
...
# vim: set filetype=yaml
