---
# Doesn't work. Ansible Galaxy is broken.
#- name: 'Install packages with xbps'
#  when: 'distro == "void"'
#  xbps:
#    name: '{{ packages }}'
#    update_cache: yes
#    upgrade_xbps: yes

- name: 'For Void Linux, ...'
  when: 'distro == "void"'
  block:
    # TODO: failed_when
    - name: 'Update xbps index'
      command:
        argv:
          - '/bin/xbps-install'
          - '-Sy'

    # TODO: failed_when
    - name: 'Update xbps'
      command:
        argv:
          - '/bin/xbps-install'
          - '-uy'
          - 'xbps'

    # TODO: failed_when
    - name: 'Install packages with xbps'
      command:
        argv: '{{ [ "/bin/xbps-install", "-y" ] + packages }}'

- name: 'For Red Hat Enterprise Linux, ...'
  when: 'distro == "rhel"'
  block:
    # TODO: check if we need to do this actually
    - name: 'Mount disc'
      register: 'reg_mount'
      failed_when:
        - 'reg_mount.rc != 0'
        - 'e_already not in reg_mount.stderr'
        # - 'e_notfound not in reg_mount.stderr'
      vars:
        # e_notfound: 'no mount point specified'  # crappy inaccurate error
        e_already: 'already mounted'
      command:
        argv:
          - 'mount'
          - '/mnt/disc'

    # todo : UPDATE YUM
    - name: 'Install packages'
      loop: '{{ packages }}'
      package:
        name: '{{ item }}'
...
# vim: set filetype=yaml
