---
# Doesn't work. Ansible Galaxy is broken.
#- name: 'Install packages with xbps'
#  when: 'distro == "void"'
#  xbps:
#    name: '{{ packages }}'
#    update_cache: yes
#    upgrade_xbps: yes

- name: 'For Void Linux, ...'
  when: 'distro == "void"'
  block:
    # TODO: figure out failed_when for xbps-install
    # (or do this block a bit differently, and better)
    - name: 'Update xbps index'
      command:
        argv:
          - '{{ xbps_command }}'
          - '-Sy'

    # TODO: figure out failed_when for xbps-install
    - name: 'Update xbps'
      command:
        argv:
          - '{{ xbps_command }}'
          - '-uy'
          - 'xbps'

    # TODO: figure out failed_when for xbps-install
    - name: 'Install packages with xbps'
      command:
        argv: '{{ [ xbps_command, "-y" ] + packages }}'

- name: 'For Red Hat Enterprise Linux, ...'
  when: 'distro == "rhel"'
  block:
    # definitely needed
    - name: 'Mount disc'
      register: 'reg_mount'
      failed_when:
        - 'reg_mount.rc != 0'
        - 'e_mount_already not in reg_mount.stderr'
        # - 'e_mount_notfound not in reg_mount.stderr'
      command:
        argv:
          - 'mount'
          - '/mnt/disc'

    # TODO: figure out failed_when for yum check-update
    - name: 'Freshen yum data'
      command:
        argv:
          - 'yum'
          - 'check-update'

    - name: 'Install packages'
      loop: '{{ packages }}'
      package:
        name: '{{ item }}'
...
# vim: set filetype=yaml
